server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  thymeleaf:
    cache: false

  web:
    mvc:
      throw-exception-if-no-handler-found: true
    resources:
      static-locations: classpath:/static/

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
